config/routes.rb
Rails.application.routes.draw do
  resources :recrutamentos
  resources :cnhs
  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: "recrutar/dashboard#index"
  ActiveAdmin.routes(self)
  resources :talentos do
    member do
      get :confirm_email
    end
  end
  resources :quartels
  resources :idiomas
  resources :habilidades
  resources :formmilitars
  resources :formacaoacads
  resources :cursos
  resources :cidades
  resources :certificacaos
  resources :cargoocupados
  resources :areaatuacaos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quartel.rb
class Quartel < ApplicationRecord
  def name
    nome
  end
  has_many :talentos
  has_many :recrutamentos
  has_many :admin_users
  validates :nome, presence: true
  enum tipo: ["OM", "Empresa", "Órgão Público"]

  def quantos_perfis_da_om?
    talentos.count
  end
end

app/controllers/quartels_controller.rb
class QuartelsController < ApplicationController
  before_action :set_quartel, only: [:show, :edit, :update, :destroy]

  # GET /quartels
  # GET /quartels.json
  def index
    @quartels = Quartel.all
  end

  # GET /quartels/1
  # GET /quartels/1.json
  def show
  end

  # GET /quartels/new
  def new
    @quartel = Quartel.new
  end

  # GET /quartels/1/edit
  def edit
  end

  # POST /quartels
  # POST /quartels.json
  def create
    @quartel = Quartel.new(quartel_params)

    respond_to do |format|
      if @quartel.save
        format.html { redirect_to @quartel, notice: 'Quartel was successfully created.' }
        format.json { render :show, status: :created, location: @quartel }
      else
        format.html { render :new }
        format.json { render json: @quartel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quartels/1
  # PATCH/PUT /quartels/1.json
  def update
    respond_to do |format|
      if @quartel.update(quartel_params)
        format.html { redirect_to @quartel, notice: 'Quartel was successfully updated.' }
        format.json { render :show, status: :ok, location: @quartel }
      else
        format.html { render :edit }
        format.json { render json: @quartel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quartels/1
  # DELETE /quartels/1.json
  def destroy
    @quartel.destroy
    respond_to do |format|
      format.html { redirect_to quartels_url, notice: 'Quartel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quartel
      @quartel = Quartel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quartel_params
      params.fetch(:quartel, {})
    end
end

app/helpers/quartels_helper.rb
module QuartelsHelper
end

app/views/quartels/_form.html.erb
<%= form_with(model: quartel, local: true) do |form| %>
  <% if quartel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quartel.errors.count, "error") %> prohibited this quartel from being saved:</h2>

      <ul>
      <% quartel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quartels/edit.html.erb
<h1>Editing Quartel</h1>

<%= render 'form', quartel: @quartel %>

<%= link_to 'Show', @quartel %> |
<%= link_to 'Back', quartels_path %>

app/views/quartels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quartels</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quartels.each do |quartel| %>
      <tr>
        <td><%= link_to 'Show', quartel %></td>
        <td><%= link_to 'Edit', edit_quartel_path(quartel) %></td>
        <td><%= link_to 'Destroy', quartel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quartel', new_quartel_path %>

app/views/quartels/new.html.erb
<h1>New Quartel</h1>

<%= render 'form', quartel: @quartel %>

<%= link_to 'Back', quartels_path %>

app/views/quartels/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_quartel_path(@quartel) %> |
<%= link_to 'Back', quartels_path %>