config/routes.rb
Rails.application.routes.draw do
  resources :recrutamentos
  resources :cnhs
  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: "recrutar/dashboard#index"
  ActiveAdmin.routes(self)
  resources :talentos do
    member do
      get :confirm_email
    end
  end
  resources :quartels
  resources :idiomas
  resources :habilidades
  resources :formmilitars
  resources :formacaoacads
  resources :cursos
  resources :cidades
  resources :certificacaos
  resources :cargoocupados
  resources :areaatuacaos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/formmilitar.rb
class Formmilitar < ApplicationRecord
  def name
    titulo
  end
  has_many :talentos
  validates :titulo, presence: true
end

app/controllers/formmilitars_controller.rb
class FormmilitarsController < ApplicationController
  before_action :set_formmilitar, only: [:show, :edit, :update, :destroy]

  # GET /formmilitars
  # GET /formmilitars.json
  def index
    @formmilitars = Formmilitar.all
  end

  # GET /formmilitars/1
  # GET /formmilitars/1.json
  def show
  end

  # GET /formmilitars/new
  def new
    @formmilitar = Formmilitar.new
  end

  # GET /formmilitars/1/edit
  def edit
  end

  # POST /formmilitars
  # POST /formmilitars.json
  def create
    @formmilitar = Formmilitar.new(formmilitar_params)

    respond_to do |format|
      if @formmilitar.save
        format.html { redirect_to @formmilitar, notice: 'Formmilitar was successfully created.' }
        format.json { render :show, status: :created, location: @formmilitar }
      else
        format.html { render :new }
        format.json { render json: @formmilitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formmilitars/1
  # PATCH/PUT /formmilitars/1.json
  def update
    respond_to do |format|
      if @formmilitar.update(formmilitar_params)
        format.html { redirect_to @formmilitar, notice: 'Formmilitar was successfully updated.' }
        format.json { render :show, status: :ok, location: @formmilitar }
      else
        format.html { render :edit }
        format.json { render json: @formmilitar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formmilitars/1
  # DELETE /formmilitars/1.json
  def destroy
    @formmilitar.destroy
    respond_to do |format|
      format.html { redirect_to formmilitars_url, notice: 'Formmilitar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formmilitar
      @formmilitar = Formmilitar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formmilitar_params
      params.fetch(:formmilitar, {})
    end
end

app/helpers/formmilitars_helper.rb
module FormmilitarsHelper
end

app/views/formmilitars/_form.html.erb
<%= form_with(model: formmilitar, local: true) do |form| %>
  <% if formmilitar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formmilitar.errors.count, "error") %> prohibited this formmilitar from being saved:</h2>

      <ul>
      <% formmilitar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formmilitars/edit.html.erb
<h1>Editing Formmilitar</h1>

<%= render 'form', formmilitar: @formmilitar %>

<%= link_to 'Show', @formmilitar %> |
<%= link_to 'Back', formmilitars_path %>

app/views/formmilitars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formmilitars</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formmilitars.each do |formmilitar| %>
      <tr>
        <td><%= link_to 'Show', formmilitar %></td>
        <td><%= link_to 'Edit', edit_formmilitar_path(formmilitar) %></td>
        <td><%= link_to 'Destroy', formmilitar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Formmilitar', new_formmilitar_path %>

app/views/formmilitars/new.html.erb
<h1>New Formmilitar</h1>

<%= render 'form', formmilitar: @formmilitar %>

<%= link_to 'Back', formmilitars_path %>

app/views/formmilitars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_formmilitar_path(@formmilitar) %> |
<%= link_to 'Back', formmilitars_path %>