config/routes.rb
Rails.application.routes.draw do
  resources :recrutamentos
  resources :cnhs
  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: "recrutar/dashboard#index"
  ActiveAdmin.routes(self)
  resources :talentos do
    member do
      get :confirm_email
    end
  end
  resources :quartels
  resources :idiomas
  resources :habilidades
  resources :formmilitars
  resources :formacaoacads
  resources :cursos
  resources :cidades
  resources :certificacaos
  resources :cargoocupados
  resources :areaatuacaos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cnh.rb
class Cnh < ApplicationRecord
  def name
    titulo
  end
  has_and_belongs_to_many :talentos
  validates :titulo, presence: true
end

app/controllers/cnhs_controller.rb
class CnhsController < InheritedResources::Base

  private

    def cnh_params
      params.require(:cnh).permit()
    end

end

app/helpers/cnhs_helper.rb
module CnhsHelper
end

app/views/cnhs/_form.html.erb
<%= form_with(model: cnh, local: true) do |form| %>
  <% if cnh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cnh.errors.count, "error") %> prohibited this cnh from being saved:</h2>

      <ul>
      <% cnh.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cnhs/edit.html.erb
<h1>Editing Cnh</h1>

<%= render 'form', cnh: @cnh %>

<%= link_to 'Show', @cnh %> |
<%= link_to 'Back', cnhs_path %>

app/views/cnhs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cnhs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cnhs.each do |cnh| %>
      <tr>
        <td><%= link_to 'Show', cnh %></td>
        <td><%= link_to 'Edit', edit_cnh_path(cnh) %></td>
        <td><%= link_to 'Destroy', cnh, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cnh', new_cnh_path %>

app/views/cnhs/new.html.erb
<h1>New Cnh</h1>

<%= render 'form', cnh: @cnh %>

<%= link_to 'Back', cnhs_path %>

app/views/cnhs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cnh_path(@cnh) %> |
<%= link_to 'Back', cnhs_path %>